elation.require("engine.engine", function() {
  elation.engine.create("test", ["physics", "controls", "sound", "ai", "world", "admin", "render"], function(engine) {
    engine.systems.world.load({ 
      "name":"ground",
      "parentname":"",
      "type":"terrain",
      "properties":{
        "position":[0,-4,0],
        "persist":true,
        "textures.map":"/media/vrcade/textures/carpet-stars.jpg",
        "textures.mapRepeat":[100,100],
        "textures.normalMap":"/media/vrcade/textures/carpet-normal.jpg"
      },
      "things":{
        "sun":{
          "name":"sun",
          "parentname":"",
          "type":"light",
          "properties":{
            "position":[-40,30,25],
            "persist":true,
            "type":"directional",
            "intensity":0.6
          }
        },
        "pacman":{
          "name":"pacman",
          "parentname":"",
          "type":"arcadecabinet",
          "properties":{
            "position":[0,0,2.25],
            "persist":true,
            "gamename":"pacman", 
            "loader":"messloader", 
            "render.gltf":"/media/vrcade/models/pacman/pacman.json"
          }
        },
        "galaxian":{
          "name":"galaxian",
          "parentname":"",
          "type":"arcadecabinet",
          "properties":{
            "persist":true,
            "position":[-2.25,0,0],
            "orientation":[0,-0.7071067811865474,0,0.7071067811865475],
            "gamename":"galaxian", 
            "render.gltf":"/media/vrcade/models/galaga/galaga.json" 
          }
        },
        "joust":{
          "name":"joust",
          "parentname":"",
          "type":"arcadecabinet",
          "properties":{
            "position":[2.25,0,0],
            "orientation":[0,0.7071067811865474,0,0.7071067811865475],
            "persist":true,
            "gamename":"joust", 
            "render.gltf":"/media/vrcade/models/joust/joust.json"
          }
        },
        "moonpatrol":{
          "name":"moonpatrol",
          "parentname":"",
          "type":"arcadecabinet",
          "properties":{
            "position":[0,0,-2.25],
            "orientation":[0,1,0,0],
            "persist":true,
            "gamename":"mpatrol", 
            "render.gltf":"/media/vrcade/models/moon-patrol/moon-patrol.json"
          }
        },
      } 
    });
    engine.start();
    var view = elation.engine.systems.render.view("main", elation.html.create({ tag: 'div', append: document.body }), { fullsize: 1, picking: 1, engine: 'test', showstats: true } );
  });
});

